### ISSUE TITLE
Better login and signup page 

### ISSUE THREAD

**Issue by ayan-joshi** [chirantanbanik/Wellread#1]
![image](https://github.com/chirantanbanik/Wellread/assets/96243602/33cb673d-4ff9-48af-81dd-8d4e2a1bfc21)

So the login page can have better css , I will fix both the pages login and sginup assign me this issue 
@chirantanbanik

**Comment by IbrahimDev00** [comment]
Please assign this to me!
GSSoc'24 contributor

**Comment by Shariq2003** [comment]
I have a good Figma Design for the Login/ Signup page and I am ready to contribute to it. Please assign this task to me.

**Comment by chirantanbanik** [comment]
You all can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by Shariq2003** [comment]
@chirantanbanik sir thanks for assigning this task to us.


@ayan-joshi @IbrahimDev00 we can connect with each other for better understanding and task division for an optimised contribution.

**Comment by IbrahimDev00** [comment]
@chirantanbanik i have created a pull request for this issue.

**Comment by ayan-joshi** [comment]
@chirantanbanik I didn't get it how we three can work on this ?

**Comment by Shariq2003** [comment]
@chirantanbanik I have created a PR for Login/Signup and Landing Page Enhancement.

**Comment by chirantanbanik** [comment]
@ayan-joshi it's for all of you to get experience on open source projects. You all have different ideas which will provide a diverse way of enhancing the project.

**Comment by IbrahimDev00** [comment]
@Shariq2003 You have copied my code without my permission.May I know how this is justifiable?

**Comment by chirantanbanik** [comment]
Guys please use fair means for your work, it's for you and your creativity. I'm closing this issue as the PR don't allign with the Project structure.
