### ISSUE TITLE
Content flowing outside headers needs to fix

### ISSUE THREAD

**Issue by kapilG0** [chirantanbanik/Wellread#100]
**Is your feature request related to a problem? Please describe.**
![Screenshot_20240604_121754](https://github.com/chirantanbanik/Wellread/assets/59639410/94a21a08-efd2-4fbb-b3ca-dc1621bf2a11)

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kapilG0** [comment]
Hello @chirantanbanik please assign this issue to me under gssoc 24

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by chirantanbanik** [comment]
@kapilG0 This issue has been resolved few hours ago under the issue #94. You can now look into other issues and work on them.
