### ISSUE TITLE
Want to Add Forgot Password Functionality

### ISSUE THREAD

**Issue by nishant0708** [chirantanbanik/Wellread#104]
Want to Add Forgot Password Functionality
I will write backend of it .In this what we can do is we can send password reset link to user through which he can reset his Id password

**Comment by dhruvgupta0503** [comment]
Hey @nishant0708 , You want to work on this issue under Girlscript Summer of code?

**Comment by nishant0708** [comment]
Yes

**Comment by dhruvgupta0503** [comment]
Can you please elaborate on how are you going to implement this

**Comment by nishant0708** [comment]
See what i will do is ask user for his email in his email he will get reset password link when he click on that he will be redirected to new page where he can reset his password

**Comment by nishant0708** [comment]
https://github.com/chirantanbanik/Wellread/assets/101548649/5280cf76-c5c2-4830-a9af-0b1e273e0c41

you can see it for reference .

**Comment by chirantanbanik** [comment]
@nishant0708 I really appreciate your effort to work on this issue but it has been solved few hours ago under issue #84. You can look into other issues and @dhruvgupta0503 will help will help you out with it.
