### ISSUE TITLE
About us Page and Features Page are not visible. 

### ISSUE THREAD

**Issue by r7projects-shayan** [chirantanbanik/Wellread#105]
**Is your feature request related to a problem? Please describe.**
The About Us and Features Pages are not visible even after logging in with an account. 

**Describe the solution you'd like**
The About Us and Features Page must be visible to all visitors 

**Additional context**

![Screenshot 2024-06-05 190846](https://github.com/chirantanbanik/Wellread/assets/167475552/2080d638-6b30-470e-a962-161a437e095e)

![Screenshot 2024-06-05 190827](https://github.com/chirantanbanik/Wellread/assets/167475552/f624a62c-c6c6-4d2c-ad51-5777e6be9492)

**Comment by r7projects-shayan** [comment]
@chirantanbanik Kindly assign me this issue so that I can fix it soon

**Comment by chirantanbanik** [comment]
The About us Page and Features Page will only be visible to the users before the login. After logging in to Wellread it sould not be visible as per project ideation.
