### ISSUE TITLE
Improve Homepage UI

### ISSUE THREAD

**Issue by harini-1597** [chirantanbanik/Wellread#107]
**Describe the bug**
The existing navbar looks very good, the rounded blue matches the background;
But, the other part of the webpage is not as expected, the white doesn;t match the overall aesthetic of the page

**Expected behavior**
I'd like to match the navbar and the extra page, by adding similar effects, thus improving the UI

**Screenshots**
![Screenshot 2024-06-06 171806](https://github.com/chirantanbanik/Wellread/assets/128628820/efb7f416-6907-45ae-b898-d85e7f67b7b8)
![Screenshot 2024-06-06 171815](https://github.com/chirantanbanik/Wellread/assets/128628820/ea7ebb07-5a26-47e3-976a-ca27a895851e)

Do assign this issue to me under the gssoc label

**Comment by chirantanbanik** [comment]
@harini-1597 As of now the Home page UI will be as it is. You can look into other issues and work on them.
