### ISSUE TITLE
Create an attractive Footer

### ISSUE THREAD

**Issue by harini-1597** [chirantanbanik/Wellread#108]
**Describe the bug**
Currently the website lacks a proper footer, thus not allowing for faster access to necessary links.

**Expected behavior**
I'd like to add a footer that has attractive icons, keeps up with the current blue theme of the restaurant and redirects to all important links, like About, Github code, Made by, YT, etc

**Screenshots**
the footer could look sth like this (in blue color):
![maxresdefault (1)](https://github.com/chirantanbanik/Wellread/assets/128628820/863189a8-a1c8-48dc-8554-6aecd8f992d0)

**Comment by chirantanbanik** [comment]
@harini-1597 The Footer is not a part of the plan as it do not satisfy the project requirement. You can look into other issues and work on them.
