### ISSUE TITLE
Feat : Adding hover effect on Feature Cards

### ISSUE THREAD

**Issue by adityas-github** [chirantanbanik/Wellread#109]
**Is your feature request related to a problem? Please describe.**
When browsing the features section of our website, the feature cards currently lack interactive elements. This makes the user experience feel static and less engaging. Users might overlook some important features because the cards do not visually stand out when interacted with.

**Describe the solution you'd like**
I would like to add a hover effect to the feature cards so that when a user hovers over a card, it scales up slightly. This visual cue can make the cards feel more interactive and highlight the features more effectively. Here is a proposed implementation in CSS:

**Describe alternatives you've considered**
Adding a different type of hover effect such as a shadow or color change.
Using animations instead of a simple scale effect to make the cards bounce or rotate slightly.

**Screenshot:**
![image](https://github.com/chirantanbanik/Wellread/assets/98210910/74bdbe1d-5eb6-427b-b5d0-cd39e3353403)

**Record**
- [x] I agree to follow this project's Code of Conduct
- [x] I'm a GSSOC'24 contributor
- [x] I want to work on this issue

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
