### ISSUE TITLE
Adding a close button on the  login form.

### ISSUE THREAD

**Issue by supriyajathar** [chirantanbanik/Wellread#113]
Is your feature request related to a problem? Please describe.
Yes, There should be a closing button on the login form.

Describe the solution you'd like
want to add a close button on the login form.

<img width="458" alt="Screenshot 2024-06-07 194127" src="https://github.com/chirantanbanik/Wellread/assets/116477978/8a9db064-3a4a-4d55-bbe5-ec12b79466e8">

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by supriyajathar** [comment]
<img width="472" alt="login form" src="https://github.com/chirantanbanik/Wellread/assets/116477978/cc853175-f84b-4452-bde0-93a415f08a32">
After clicking on the close button it redirects to the home page
