### ISSUE TITLE
Display Feature page instead of Login/signup Page .

### ISSUE THREAD

**Issue by YukiP7** [chirantanbanik/Wellread#114]
**Describe the bug**
Display the login and signup page when clicking on the "about" and "features" options provided in the navbar on Home Page .

**To Reproduce**
1. Go to website
2. Click on Features
3. See error

**Expected behavior**
It should be possible to navigate to the features and about us content on the home page by clicking on the corresponding options in the navbar.

**Screenshots**

https://github.com/chirantanbanik/Wellread/assets/109288720/1167c212-d4e9-4277-a8f7-46e90c7a530c

**Additional context**
Please assign me this issue under gssoc with its appropriate level labels.

**Comment by YukiP7** [comment]
@chirantanbanik Please assign me this issue under gssoc with its appropriate level labels.

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by YukiP7** [comment]
Hey @chirantanbanik I have raised a pull request for the solution of this issue , Please review the changes and do merge it out .

**Comment by chirantanbanik** [comment]
@YukiP7 what is the status of this issue, there was merge conflict in the previous PR you raised. Did you work in resolving it?
