### ISSUE TITLE
[Feat]: Create Issue forms and make the issue options more visually appealing

### ISSUE THREAD

**Issue by TonyStark-47** [chirantanbanik/Wellread#116]
### Currently, there is an issue template for this repo, but no issue form which will help users in contributing.

- #### I will add Issue Forms to the respective issues to make it easier for the contributor to raise it.
#### Here is an example of how a Bug Issue Form will look like 👇

![image](https://github.com/apu52/METAVERSE/assets/73957207/4c6889aa-3abf-485d-9c41-09f1f562a0aa)

- and issue templates:

![image](https://github.com/apu52/METAVERSE/assets/73957207/6827e4a8-5382-4376-bbf6-afb9f9731252)

**Comment by TonyStark-47** [comment]
I want to work on this issue. So, kindly assign this issue to me ( GSSOC'24 ).

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by TonyStark-47** [comment]
Hey @chirantanbanik, I have raised a PR #123 related to this issue. Please check it out.
