### ISSUE TITLE
[Bug] : Home page is not responsive

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#118]
**Describe the bug**

@chirantanbanik 

check this out,
in responsive devices, home page design changed

**To Reproduce**
1. Go to 'home page'
2. try to see that page in responsive devices

**Expected behavior**

**Screenshots**

![image](https://github.com/chirantanbanik/Wellread/assets/114583978/16e38076-39c6-4fbb-b100-84a5086440c5)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chirantanbanik** [comment]
This issue is also under the issue #94
