### ISSUE TITLE
Ui Improvement

### ISSUE THREAD

**Issue by TejasNasre** [chirantanbanik/Wellread#12]
# Problem 
Currently The Ui Is Not Good And The User Experience Is Not Good.Adding More Ui And Make Application More Beautiful leads to gain more users and good interaction.
  
# Solution
Adding More Ui Components ex.Footer , Header , Hero Section And More Dynamic Ui With Responsive Ui And Seamless Interaction.

# Ui Library
Using Tailwind Css and Tailwind Css Ui Library We Can Use  

Figma File : [https://www.figma.com/design/uBl2GsyzvXmM7nBhSFmeu1/Free-Blog-Website-Template-(Community)?node-id=0-1&t=gOm1GqJ4Qqrafu9n-0](Figma Design)
If You Love We Can Add This Ui To Blog Website

**Comment by TejasNasre** [comment]
Please Assign This Issue To Me.

**Comment by Shariq2003** [comment]
Please Assign this task to me sir, It will be a great opportunity for me.

**Comment by TejasNasre** [comment]
The application ui is big we can work on ui components by dividing the work together

**Comment by TejasNasre** [comment]
@chirantanbanik we you please look on this issue and divide the whole Ui Upgradation to us because the ui is little big.

**Comment by Nikhilsaini481-tech** [comment]
@chirantanbanik can you please assign ui work to me i have 6 months experience in react.js and tailwind.

**Comment by chirantanbanik** [comment]
This issue won't be worked on as of now.
