### ISSUE TITLE
Add card in the home screen 

### ISSUE THREAD

**Issue by namandude** [chirantanbanik/Wellread#121]
Hey i would like to create the cards in the home screen where the swiper effect is added the popular blogs will be there which adding the next level user experiennce in it .
There will be the swiper class , cards animation , framer motion will be used  .

![image](https://github.com/chirantanbanik/Wellread/assets/118013565/2ec287b4-c8ea-4722-ac64-82f7df8118e2)
 Like thsi there will be swiper cards

Please assign this me under gssoc i would like to work on this.

**Comment by chirantanbanik** [comment]
@namandude As of now we won't be taking this issue, you can look into other issues an work on them.
