### ISSUE TITLE
[style] Make the navbar sticky

### ISSUE THREAD

**Issue by root-0101** [chirantanbanik/Wellread#127]
It would be great if we make the navbar sticky. so, it is easier to navigate to the users and also improve the UI

![Screenshot 2024-06-09 210134](https://github.com/chirantanbanik/Wellread/assets/142779809/f80a70d0-b84d-4d29-b252-7377bd20e8b7)

**Comment by chirantanbanik** [comment]
Duplicate issue of the issue #99
