### ISSUE TITLE
Adding a hero image

### ISSUE THREAD

**Issue by root-0101** [chirantanbanik/Wellread#129]
A hero image is the center of attraction for a web page. so, adding an hero image to the home page will enhance the user experience.

**Comment by root-0101** [comment]
We need to add a hero image in the main for which enhance the UI of the page and nowadays user prefer to have some sort of visual which provides the idea of the whole webpage 

![Screenshot 2024-06-11 220514](https://github.com/chirantanbanik/Wellread/assets/142779809/687fe7bc-4084-41c4-8464-b10764905bd2)

**Comment by chirantanbanik** [comment]
@root-0101 We won't be implementing anything in the Home page as of now. You can look into other issues and work on them.
