### ISSUE TITLE
 [Feature]: Add Hero Landing Page

### ISSUE THREAD

**Issue by Vaibhavsg17** [chirantanbanik/Wellread#13]
Is your feature request related to a problem? Please describe:
Currently, Wellread lacks a main hero landing page, which serves as the focal point for attracting and engaging users. Without a compelling hero landing page, the platform may struggle to effectively communicate its value proposition and capture users' attention upon initial visitation.

Describe the solution you'd like:
I propose adding a hero landing page to Wellread to create a captivating and informative entry point for users. This hero landing page will feature visually appealing design elements, concise messaging, and clear calls to action to entice users to explore further and engage with the platform. Additionally, the hero landing page will effectively communicate Wellread's key features, benefits, and unique selling points to potential users.

Describe alternatives you've considered:
One alternative solution could be to rely solely on the existing landing page layout without implementing a hero section. However, this approach may result in a less impactful and memorable user experience, potentially leading to lower user engagement and conversion rates.

Additional context:
The addition of a hero landing page is crucial for enhancing the overall user experience and driving user engagement on the Wellread platform. By creating a visually stunning and informative entry point, we can effectively communicate Wellread's value proposition and encourage users to explore the platform further. Additionally, the hero landing page will serve as a powerful tool for attracting new users and retaining existing ones, ultimately contributing to the platform's growth and success.

**Comment by Vaibhavsg17** [comment]
@chirantanbanik assign this to me under gssoc'24 & level 3

**Comment by chirantanbanik** [comment]
@Vaibhavsg17 The landing page of Wellread has been made. You can look into other issues and work on them.
