### ISSUE TITLE
💡[Feature]:  Add dark/bright mode toggle button

### ISSUE THREAD

**Issue by ananyag309** [chirantanbanik/Wellread#133]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Nowadays people prefer to work and use website in dark mode. please assign this issue to me under gssoc

### Use Case

If we add mode button it will help user to use website acc to their preferable mode providing comfortability which will have a positive outcome for the website

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@ananyag309 For Wellread we will not be implementing the Dark mode feature as it there will be lot of other changes which needs to be made implemented first.
