### ISSUE TITLE
📝[Docs]:  Update readme with new screenshots and enhance the readme file more

### ISSUE THREAD

**Issue by ananyag309** [chirantanbanik/Wellread#134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Issue Description

Currently the readme file previews old screenshots i want to replace it with the current ones. 

### Suggested Change

I will try to enhance it more by adding some more elements. please assign me this issue under gssoc

### Urgency

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@ananyag309 Ananya the screenshots that are present there are for the contributors to setup appwrite with their account. You should not replace it.

**Comment by ananyag309** [comment]
ok sure i will do it

**Comment by chirantanbanik** [comment]
@ananyag309 I have created a new branch docs, you need to make a **README.md** file there and work.
