### ISSUE TITLE
💡[Feature]: Build a Testimonials Page with sliding carousel

### ISSUE THREAD

**Issue by komal-agarwal5** [chirantanbanik/Wellread#140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

I wish to add a Testimonials Page with sliding carousel wherein the review of the users can be displayed.

### Use Case

This will attract more users to the website.

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@komal-agarwal5 We won't have implementing the testimonials page for Wellread. You can look into other issues and work on them.
