### ISSUE TITLE
💡[Feature]: Add more password constraints

### ISSUE THREAD

**Issue by AnanyaJain25** [chirantanbanik/Wellread#141]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

While creating a password application it only shows password constraint to be 8

### Use Case

8 length passowrd could be easily cracked and users credentials can be unlocked effecting user secuity

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
We will not be needing this feature.
