### ISSUE TITLE
💡[Feature]: Google auth implementation

### ISSUE THREAD

**Issue by mukilan2815** [chirantanbanik/Wellread#144]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Adding google oneclick auth functionality makes users to easily signin and signup.

### Use Case

Adding google auth can make users to easily signin

### Add ScreenShots

![image](https://github.com/chirantanbanik/Wellread/assets/71129858/0a838515-b724-499c-8d15-bf0f121dd1d2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@mukilan2815 We won't be taking this issue, you can look into other issues and work on them.
