### ISSUE TITLE
Fix the Navbar at top to make it usable from anywhere in website

### ISSUE THREAD

**Issue by Utsavladia** [chirantanbanik/Wellread#145]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

The Navbar should be fixed at the top to access it from anywhere and used to navigate.

### Use Case

The user can use it from anywhere to go to different pages.

### Add ScreenShots

![image](https://github.com/chirantanbanik/Wellread/assets/124615886/88f2a9ca-e154-40c5-9dcf-4193670f82d2)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@Utsavladia The navbar will not be worked on as it server it's purpose perfectly. You can look into other issues and work on them.
