### ISSUE TITLE
💡[Feature]: Adding close button to the signup page

### ISSUE THREAD

**Issue by supriyajathar** [chirantanbanik/Wellread#149]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

Add a close button to the Signup form

### Use Case

After clicking the close button, it will redirect the user to the home page.

### Priority

Medium

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by supriyajathar** [comment]
Please, assign this task to me

**Comment by dhruvgupta0503** [comment]
Hi, @supriyajathar Can you please elaborate more about this issue 

Once that is complted, I will assign this issue to you

**Comment by chirantanbanik** [comment]
@dhruvgupta0503 She has worked on the same issue for Login page now she will do it for Signup page. It's a feature which will help users to close the Signup page with a small cross icon in the top left side of the page.
