### ISSUE TITLE
UI Improvement : Login and SignUp Page.

### ISSUE THREAD

**Issue by ira-mane** [chirantanbanik/Wellread#15]
The entire page appears blank except for the navigation bar, which offers the options to either log in or sign up. We need to implement dedicated sign-up and login pages with improved user interface, featuring appropriate buttons and themes.
![image](https://github.com/chirantanbanik/Wellread/assets/108334485/1a352145-8b33-4db6-afdc-5effe34157eb)

@chirantanbanik Can you assign me this issue ?

**Comment by chirantanbanik** [comment]
@ira-mane as of now you work on the blank page enhancement. The work on the login and signup component has been taken up by many contributors. Try to come up with an idea under the navbar.
Go through the code part and understand it. Then, you must read CONTRIBUTING.MD and README.md and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

Regards,
Chirantan Banik

**Comment by ira-mane** [comment]
sure @chirantanbanik so as of now I have to work on UI part of the page which is blank.  I will update on the solution of that part.
Could you please expand on navbar part ? :- "Try to come up with an idea under the navbar."

**Comment by Shariq2003** [comment]
I Have fixed the blank page issue along with the Login and Signup Page UI Enhancement.
Just going to make the PR

**Comment by Tanishka023** [comment]
Can you please assign issue #15 if nobody is working on it

**Comment by chirantanbanik** [comment]
This issue has been resolved.
