### ISSUE TITLE
BUG🐞 :  Fix Navigation Issue in Navbar For About and Features Section

### ISSUE THREAD

**Issue by aslams2020** [chirantanbanik/Wellread#154]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

Hey @chirantanbanik,
Here is the issue I encountered - 

Currently, when users click on the "About" and "Features" links in the navbar, they are **incorrectly redirected to the "Login" page**, despite the "About" and "Features" sections being present on the website. 
This behavior **affects the user experience** by not allowing users to access the "About" and "Features" sections directly from the navbar.

### Expected behavior

Clicking on the "About" and "Features" links in the navbar should scroll the page to the respective sections without redirecting to the "Login" page.

**Proposed Solution:**
- Ensure that the links are correctly pointing to the respective sections within the same page.
- Modify the links to prevent redirection to the "Login" page.

### Add ScreenShots

Here is the Video depicting the issue - 

https://github.com/chirantanbanik/Wellread/assets/131389695/e5c8bf27-b14c-4ba4-880f-f7b87a1f5911

@chirantanbanik, Could you please assign me this issue under GSSOC'24?

### What browsers are you seeing the problem on?

Chrome

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by YukiP7** [comment]
hey @aslams2020 @chirantanbanik  I am already working on this issue and also created a pull request

**Comment by chirantanbanik** [comment]
@YukiP7 As you have just now made an PR so before that I made sure everyone should get a chance to work. Now as the PR is being merged so @aslams2020 you can look into other issues and work on them.
