### ISSUE TITLE
Footer with navigation links

### ISSUE THREAD

**Issue by lovelyANSH2410** [chirantanbanik/Wellread#16]
There isn't any footer page in this app i can make an attractive on also i'll add social media icons and pages like about us and contact us etc. also i'll create those pages and add the navigation to the links.

also i can add a good looking background like this to improve the UI and make it look good with existing UI. I can it if works very well.

![image](https://github.com/chirantanbanik/Wellread/assets/110022447/8e1e35e9-a739-4617-a9fd-2994334b24a2)

**Comment by chirantanbanik** [comment]
We don't require these things due to non-alignment with the project.
