### ISSUE TITLE
💡[Feature]: Google oauth

### ISSUE THREAD

**Issue by mukilan2815** [chirantanbanik/Wellread#167]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

We can add Google auth for one click loggin in so that user can easily login

### Use Case

Reduces the time and remembering the password.

### Add ScreenShots

![image](https://github.com/chirantanbanik/Wellread/assets/71129858/bb01c397-ced9-4d2e-86e0-c1b0e8f784dc)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@mukilan2815 Look into the announcement #166 in the Discussions and we will not be implementing Google auth for Wellread.
