### ISSUE TITLE
💡[Feature]:  alignment of card texts

### ISSUE THREAD

**Issue by DevGajjar28** [chirantanbanik/Wellread#169]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

card content/text does not contain an alignment of view.

### Use Case

alignment provide better UI to user , user-friendly interface. 

### Add ScreenShots

![image](https://github.com/chirantanbanik/Wellread/assets/145287513/9b967d29-3f89-4466-aa26-bfc42d9a1995)

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [ ] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by chirantanbanik** [comment]
@DevGajjar28 Look into the announcement #166 in the Discussions.
