### ISSUE TITLE
🐞[Bug]: Inconsistency in capitalization and formatting of README.md file

### ISSUE THREAD

**Issue by Aditi22Bansal** [chirantanbanik/Wellread#175]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the bug

I noticed some inconsistencies in capitalization and a few areas where formatting can be improved for clarity.

### Expected behavior

Improve clarity

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Aditi22Bansal** [comment]
@chirantanbanik 
Kindly assign me this issue with label

**Comment by chirantanbanik** [comment]
@Aditi22Bansal Look into #166 and issues like this we are not taking. You can look into other issues and work on them.
