### ISSUE TITLE
Create a logo for this website

### ISSUE THREAD

**Issue by SrijaAdhya12** [chirantanbanik/Wellread#18]
**Is your feature request related to a problem? Please describe.**
The website lacks a proper logo

**Describe the solution you'd like**
- I want to create a logo according to the color scheme of the website to connect better with users
- Add the logo as favicon
- Add the logo to the navbar

**Describe alternatives you've considered**

**Additional context**
![image](https://github.com/chirantanbanik/Wellread/assets/113666002/dfbc3749-8cbe-4c17-95b1-9105b89574b5)
The website has no logo and favicon

**Comment by 22-0304** [comment]
Can you assign me this issue @chirantanbanik

**Comment by chirantanbanik** [comment]
You both can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show 3 logos each. Will see which logo fits best to the project requirement.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by SrijaAdhya12** [comment]
> You both can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant. After you are done with the solution to the issue, you have to show 3 logos each. Will see which logo fits best to the project requirement.
> 
> All the best, and do well.
> 
> Regards, Chirantan Banik


logo 1:
![Wellread logo 1 copy](https://github.com/chirantanbanik/Wellread/assets/113666002/ebb5a888-9718-46d3-9281-886bab6da22f)


logo 2: 

![Wellread logo2 copy](https://github.com/chirantanbanik/Wellread/assets/113666002/e511bee9-0545-4167-84c2-3dc7348e9f01)


logo 3:

![Wellread logo 3 (1)](https://github.com/chirantanbanik/Wellread/assets/113666002/15663ae6-76ab-417d-883e-2733de4ccfdb)

I have made this 3 logos. Please have a look onto them.

**Comment by chirantanbanik** [comment]
@SrijaAdhya12 make an PR of the third logo.
