### ISSUE TITLE
Add Functionality: Improvements to the All Posts Page and navigation bar

### ISSUE THREAD

**Issue by manasvinaik** [chirantanbanik/Wellread#21]
The All Posts Page seems empty and can be improved upon in terms of design and functionality.

I want to enhance the attractiveness of the site by updating the layout of all posts and adding a section for top posts to increase user interest.
Adding a functionality to 'like' the posts can also be implemented.

I have worked on many now online websites and am confident that I can make these improvements. @chirantanbanik Please assign this issue to me under the tag GsSOC'24. Thank you.

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
