### ISSUE TITLE
Blank Page Issue After Login

### ISSUE THREAD

**Issue by Shariq2003** [chirantanbanik/Wellread#23]
**Describe the bug**
After Login, All the Posts Should be Visible (Initally it is a blank page)

![image](https://github.com/chirantanbanik/Wellread/assets/109452033/cd5b231a-316a-4fd9-9c80-a0038c6e63d2)

Please Assing this issue to me

**Comment by chirantanbanik** [comment]
@Shariq2003 This issue has been fixed. You can look into other issues.
