### ISSUE TITLE
[FEAT]:UI/UX Improvement in Home page, Add Post, and All Post 

### ISSUE THREAD

**Issue by HARISH-1222** [chirantanbanik/Wellread#26]
I like the concept of the page.

But We Need to improve the UI/UX 

<img width="1280" alt="Screenshot 2024-05-13 at 8 10 12 AM" src="https://github.com/chirantanbanik/Wellread/assets/83270411/9ef5aea0-f8c0-4acd-8e69-47d6d2cfa331">

<img width="1280" alt="Screenshot 2024-05-13 at 8 16 55 AM" src="https://github.com/chirantanbanik/Wellread/assets/83270411/9bd28140-a9c6-4869-a504-d5726569e417">

#15 Started login/signup page 

let me Complete the home page, Add Post, and All Post and make a Loader.

If you like, I will be happy to contribute under GSSC

**Comment by chirantanbanik** [comment]
@HARISH-1222 Now we are looking for the designing of the All post and Add post page. The Home page is already been designed. You can look into other issues and work on them.
