### ISSUE TITLE
Filter genuine email

### ISSUE THREAD

**Issue by pankaj-bind** [chirantanbanik/Wellread#27]
**Is your feature request related to a problem? Please describe.**
In your application anyone can enter using **temporary or disposable email**.

**Describe the solution you'd like**
I will add a feature so that no one could create an account using **temporary or disposable email**.
It will allow only genuine users in your database.
It will help to avoid any bot.

**Describe alternatives you've considered**

**Additional context**
Assign me this work under GSSoC24, I will implement it.

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
