### ISSUE TITLE
Validations are missing in the login page

### ISSUE THREAD

**Issue by Niharika0104** [chirantanbanik/Wellread#29]
**Is your feature request related to a problem? Please describe.**
I would like to add validation in the login page.

**Describe the solution you'd like**
I will use react toastify to show the validations

**Comment by DownOnCoffee** [comment]
As an experienced frontend developer, I noticed that the login page on your website lacks necessary validations for user input. This absence could potentially lead to issues with user data integrity and security.
To address this, I propose to implement comprehensive input validations, including-
->checks for correct email formats
->password strength requirements
->Uppercase and lowercase senstivity
->Add confirm password

This will ensure that all user inputs meet our security standards before submission. This task aligns well with my skills, and I am eager to take it on as part of my contributions in GSSOC'24. Could you please assign this task to me?

**Comment by dhruvgupta0503** [comment]
Hi, @Niharika0104 @DownOnCoffee  I want both of you to collabrate on this issue 
I am going to assign this issues to both of you

**Comment by JaiBansal007** [comment]
I want to work on this issue . Could you please assign this task to me?. I will Add Zod Schema for Validation .  @chirantanbanik

**Comment by dhruvgupta0503** [comment]
@JaiBansal007  the issue is already assigned, we have to give everyone a fair chance. You can check out other issues, the ones which are not assigned and make a PR. Along with this you have to elaborate us on how you are going to solve this issue. Then you are good to go.
