### ISSUE TITLE
Making font, background and navbar more decorative.

### ISSUE THREAD

**Issue by Rakshit-gen** [chirantanbanik/Wellread#3]
**Is your feature request related to a problem? Please describe.**
The background and font along with navbar look pretty simple and not decorated.

**Describe the solution you'd like**
A better looking background and navbar along with font.

**Describe alternatives you've considered**
1. Using larger font with a little decoration
2. Using an eye catching classic gradient for the background
3. Using better colour theme and design with padding for the navbar

**Additional context**
I am a contributor for GSSoC 2024. Please assign this issue to me!

**Comment by IbrahimDev00** [comment]
Please assign this issue to me, and do add labels too please.
GSSoc '24 contributor

**Comment by chirantanbanik** [comment]
You both can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by anshulsoni4** [comment]
@chirantanbanik hey, can you assign me this issue I can work it now only
