### ISSUE TITLE
Feat:Confirm password field is missing on the registration page

### ISSUE THREAD

**Issue by Niharika0104** [chirantanbanik/Wellread#30]
**Is your feature request related to a problem? Please describe.**
I see that confirm password field is missing on the registration page.I would like to add that as it will help users in quickly differentiating the sign in and sign up pages and would give a look and feel of the modern website.

**Describe the solution you'd like**
I will add one more field to the form and manage necessary validations required for it.

**Comment by chirantanbanik** [comment]
@Niharika0104 It is not that important to add a confirm password in the registration page. You can look into other critical issues and work on them.
