### ISSUE TITLE
Feat:Validations are missing on the registration page

### ISSUE THREAD

**Issue by Niharika0104** [chirantanbanik/Wellread#31]
**Is your feature request related to a problem? Please describe.**
I see validations are missing on the registration page.

**Describe the solution you'd like**
I will add validations using react-toastify library

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
