### ISSUE TITLE
Proper toasts for errors

### ISSUE THREAD

**Issue by DownOnCoffee** [chirantanbanik/Wellread#35]
**Describe the bug**
A toast is a better format for wrong password alerts,errors or invalid email error etc. In this screenshot you see how the error is coming which is not best way to display errors . This shouldnt be there "Invalid `password` param: ".
![image](https://github.com/chirantanbanik/Wellread/assets/94672955/5ca26b37-ad92-41ea-abd6-c10438051c92)

**To Reproduce**
I will convert all the error messages to an error toast like this 
![Screenshot (1187)](https://github.com/chirantanbanik/Wellread/assets/94672955/232e3ea8-51f0-474a-8ea9-94c044399529)
Its a better way to show errors . I can implement this on signup/login pages and any other page where you have to display alerts.

**Comment by DownOnCoffee** [comment]
@chirantanbanik Can you add the required labels of gssoc and level?

**Comment by chirantanbanik** [comment]
Hello @DownOnCoffee ,  you can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by DownOnCoffee** [comment]
okay!

**Comment by DownOnCoffee** [comment]
![Screenshot (1266)](https://github.com/chirantanbanik/Wellread/assets/94672955/6086585e-c06a-4126-a9ab-e17a80d30974)
![Screenshot (1268)](https://github.com/chirantanbanik/Wellread/assets/94672955/23692a3c-0b02-4d28-8bb5-17dee8887e0f)
I applied the toast in this way on login page , if this works for you , I will do this on other pages as well!

**Comment by mtg718** [comment]
Hi @DownOnCoffee ,Please assign this issue to me under GSSoC'24.

**Comment by DownOnCoffee** [comment]
@mtg718 I am already working on it

**Comment by DownOnCoffee** [comment]
> ![Screenshot (1266)](https://private-user-images.githubusercontent.com/94672955/332277914-6086585e-c06a-4126-a9ab-e17a80d30974.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzkyOTUsIm5iZiI6MTcxNjQzODk5NSwicGF0aCI6Ii85NDY3Mjk1NS8zMzIyNzc5MTQtNjA4NjU4NWUtYzA2YS00MTI2LWE5YWItZTE3YTgwZDMwOTc0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA0MzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJiMjA5N2Y0NWVlN2E0NDUxMTM1ODczMGMxNTRlOTE1NWNiZWI4M2IxYjkwZjIwYTY4MjFhZDU5NDdkMDA1NmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.es7m6JWQhTOnyRgihHnxBOKaezqysOGdrTkmDIJddk4) ![Screenshot (1268)](https://private-user-images.githubusercontent.com/94672955/332277923-23692a3c-0b02-4d28-8bb5-17dee8887e0f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY0MzkyOTUsIm5iZiI6MTcxNjQzODk5NSwicGF0aCI6Ii85NDY3Mjk1NS8zMzIyNzc5MjMtMjM2OTJhM2MtMGIwMi00ZDI4LThiYjUtMTdkZWU4ODg3ZTBmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTIzVDA0MzYzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMDA0Yzc1YmIwMzA3YjBjMmRhOThlZmYyNTk1NzdiY2JkOWMwZmI4YjNkMTE0YTg1MGRmNDMwNTRjNDI0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._p8k3ImnsU_QswVDTTFGqJuOc4nQkZFVGqLhcCz3M2c) I applied the toast in this way on login page , if this works for you , I will do this on other pages as well! Let me know which design fits best for you. @chirantanbanik

@chirantanbanik Can you please reply so that I can continue the work

**Comment by DownOnCoffee** [comment]
@chirantanbanik Can you please reply and tell which one of those alerts you like more.

**Comment by chirantanbanik** [comment]
Hello @DownOnCoffee the first one looks better. You can craft a better alert too.

**Comment by DownOnCoffee** [comment]
@chirantanbanik okay I will craft a better alert , you want the design to be better or the content inside it?

**Comment by chirantanbanik** [comment]
The content inside it.

**Comment by DownOnCoffee** [comment]
okay ! For that I will have to change a backend code a little, as I was just displaying the content that I was getting from backend and it's coming in a format like that , so is that okay? @chirantanbanik

**Comment by chirantanbanik** [comment]
Yes sure go ahead.

**Comment by DownOnCoffee** [comment]
![Screenshot (1305)](https://github.com/chirantanbanik/Wellread/assets/94672955/6149ac89-4474-4c6d-a0bd-a394e81ffecd)
![Screenshot (1306)](https://github.com/chirantanbanik/Wellread/assets/94672955/9b5ff96a-e43c-422d-a497-4a2d47f57002)
![Screenshot (1308)](https://github.com/chirantanbanik/Wellread/assets/94672955/b985f1a4-91f7-4beb-89e4-b2586fcfd8af)
I have converted all errors and alerts to proper toasts. Should i make a pull request? @chirantanbanik

**Comment by chirantanbanik** [comment]
Great, make sure in the PR you are only pushing this changes not the **.env** changes as you have used your **.env** for the project.

**Comment by DownOnCoffee** [comment]
@chirantanbanik No I haven't done any changes in the .env file
