### ISSUE TITLE
Adding a section of My Posts 

### ISSUE THREAD

**Issue by Tanishasi** [chirantanbanik/Wellread#36]
**Is your feature request related to a problem? Please describe.**
no personalised individual page

**Describe the solution you'd like**
I would like to add a feature of profile which will contain users personal description and below it all the posts he has created and also option to add them to collection

**Additional context**
Will make it more organised and provide better UI.
I would like to work on it under GSSOC'24

**Comment by masterboy376** [comment]
Hello @chirantanbanik, I would like to work on the issue under GSSoC'24.

**Comment by chirantanbanik** [comment]
You both can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by chirantanbanik** [comment]
Closed due to inactivity.
