### ISSUE TITLE
[UI] : All Posts page is not responsive

### ISSUE THREAD

**Issue by SaranshBangar** [chirantanbanik/Wellread#38]
**Describe the bug**
The "All Posts" page is not mobile responsive

**To Reproduce**
1. Go to 'All Posts'
2. Reduce screen size
3. See error

**Expected behavior**
The posts should wrap according to the screen size

**Screenshots**
![image](https://github.com/chirantanbanik/Wellread/assets/114401238/6eb0d76a-70de-4016-9542-f0de39b3048b)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
I am a GSSoC contributor, please label this issue accordingly

**Comment by masterboy376** [comment]
Hello @chirantanbanik, I would like to work on the issue under GSSoC'24.

**Comment by chirantanbanik** [comment]
You both can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by chirantanbanik** [comment]
This issue has already been worked on and the PR has been merged. You can look into other issues @masterboy376 and @SaranshBangar.
