### ISSUE TITLE
Add Like, dislike button for readers review

### ISSUE THREAD

**Issue by krithika2543** [chirantanbanik/Wellread#40]
Introduce like and dislike buttons for each blog left by readers. These buttons will allow users to indicate whether they found the blog helpful or not quickly. 

In the all posts section, in each thumbnail of the blog, all number of likes and dislikes. Once a particular blog page is opened, the new readers can also cast their vote after reading (creating a like, dislike button)

GSSOC'2024 Contribuitor

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by krithika2543** [comment]
Yes sure. Thankyou

**Comment by krithika2543** [comment]
Hey, I see there is an issue in displaying the blogs or even creating a new
blog and submitting it. I am not able to view them in order to add this
like, dislike feature. Can you kindly check on it once. Thankyou

**Comment by mtg718** [comment]
Hi @krithika2543, please assign this issue to me under GSSoc'24.

**Comment by chirantanbanik** [comment]
Hello @krithika2543 This issue has already been worked upon Duplicate under the issue #47. You can look into other issues.
