### ISSUE TITLE
Make the add post and all post pages responsive.

### ISSUE THREAD

**Issue by Paper-Bag-dev** [chirantanbanik/Wellread#41]
**Is your feature request related to a problem? Please describe.**
- The site isn't responsive to work on lower resolution devices which makes it limited and difficult to be used on different devices.

**Describe the solution you'd like**
- To make the two main routes All Posts and Add post pages responsive.

**Current pages that require changes**
![image](https://github.com/chirantanbanik/Wellread/assets/92173476/8047565f-5802-474e-a778-d1966cc248ad)

**Comment by masterboy376** [comment]
Hello @chirantanbanik, I would like to work on the issue under GSSoC'24.

**Comment by chirantanbanik** [comment]
You both can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by chirantanbanik** [comment]
This issue has been resolved under the issue #94.
