### ISSUE TITLE
Designing The Landing Page

### ISSUE THREAD

**Issue by Lavanyaaa25** [chirantanbanik/Wellread#42]
As a user visits the site, the landing page is first rendered. In this case, the landing page is a blank blue page with only Navbar. Would lIke to design Landing page with framer motion animations as I have previous experience of doing so.

![Screenshot 2024-05-17 143823](https://github.com/chirantanbanik/Wellread/assets/114211427/5a40b7ae-5c27-4dce-89b6-6433a7fbc401)

@chirantanbanik Could you please assign this work to me?

**Comment by chirantanbanik** [comment]
Start working on it. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by YukiP7** [comment]
Hey @chirantanbanik and @Lavanyaaa25  I will love to do work with you in this issue . You can also assign me this issue .
