### ISSUE TITLE
Loading state for the login and signup form

### ISSUE THREAD

**Issue by rohansen856** [chirantanbanik/Wellread#43]
**Is your feature request related to a problem? Please describe.**
When the user presses the login or signup button after entering credentials, if they have slow internet, it takes a while to process their request. A Loading state should be shown to keep user interactivity going.

**Describe the solution you'd like**
The best course of action would be adding a loading spinner and making the login/signup button disabled while the previous equest is being processed.

**Contribution**
I would like to add the loading state to the form. Please assign me this issue under GSSOC'24.

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
