### ISSUE TITLE
Card ui

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#44]
@chirantanbanik 

**Is your feature request related to a problem? Please describe.**
Add Blog Cards

**Describe the solution you'd like**
- we can add blogs card  that contain image, title, author etc information

**Additional context**

it should look like 
![image](https://github.com/chirantanbanik/Wellread/assets/114583978/a473eac3-39ed-4fec-b6ef-da0d724a92e8)

or

![image](https://github.com/chirantanbanik/Wellread/assets/114583978/ad056627-6804-4d08-bc86-edb21c02a65c)

**Comment by chirantanbanik** [comment]
This issue is already being worked on @dhruv8433
