### ISSUE TITLE
Feat: Search functionality 

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#45]
@chirantanbanik 

**Is your feature request related to a problem? Please describe.**
- we can add serach bar that find particular blogs

**Describe the solution you'd like**
- use of api that filter blog based on user's input

**Additional context**

![image](https://github.com/chirantanbanik/Wellread/assets/114583978/e7e7dbb8-579e-48f7-b40e-08f14794a2bb)

**Comment by chirantanbanik** [comment]
@dhruv8433 How are you going to implement this feature in Wellread? Give me an detailed explanation.

**Comment by dhruv8433** [comment]
@chirantanbanik 

we can add one beautiful search bar in this page

![image](https://github.com/chirantanbanik/Wellread/assets/114583978/d6a58118-4be8-48db-a8b1-b9131388968a)

when user want to find perticular blog it will help

**Comment by dhruv8433** [comment]
we can filter blogs based on search query

**Comment by dhruvgupta0503** [comment]
Can you tell me how you are going to filter search blogs

**Comment by dhruv8433** [comment]
using js `filter` we can easily search any blogs

**Comment by dhruv8433** [comment]
Thank you @dhruvgupta0503
