### ISSUE TITLE
like and dislike a blog

### ISSUE THREAD

**Issue by Varsani2520** [chirantanbanik/Wellread#47]
Hey @chirantanbanik ,
user can able to like and dislike a post

**Comment by AyushSingh916** [comment]
Hey @chirantanbanik 
I can add the features of liking and disliking the post, please assign this task to me.

**Comment by Varsani2520** [comment]
Thanks @chirantanbanik

**Comment by AyushSingh916** [comment]
Thanks @chirantanbanik 

<img width="959" alt="Screenshot 2024-06-03 184508" src="https://github.com/chirantanbanik/Wellread/assets/133966255/3f0644ae-a4cb-4fae-8886-0647e6471403">


I have added the ui elements and raised a pr.
