### ISSUE TITLE
Feat: Add Detailed Page For Blogs Card

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#48]
@chirantanbanik 

**Is your feature request related to a problem? Please describe.**

- we can add card and on that card click we can redirect user to detialed page

**Describe the solution you'd like**
- use of `/[blog-id]/[blog-title]` route for detailed page of blogs

**Additional context**

Something like this
![image](https://github.com/chirantanbanik/Wellread/assets/114583978/dfa2f0c9-131f-4db7-a6c2-0ef62b5585b2)

**Comment by chirantanbanik** [comment]
@dhruv8433 We won't be taking this issues as it don't do along with project vision.
