### ISSUE TITLE
Bug Fixes: Signup form (Not another UI Bug fix req)

### ISSUE THREAD

**Issue by Piyusharora2003** [chirantanbanik/Wellread#5]
The idea is to add confirm password input along with a basic email check .
Currently 
![image](https://github.com/chirantanbanik/Wellread/assets/74443858/c0fcdf0b-bc10-473b-b2d6-3bbcd3e77807)
// can be signed in from any email
![image](https://github.com/chirantanbanik/Wellread/assets/74443858/cc064fff-46e2-427c-bff0-8fd7ae01253e)

![image](https://github.com/chirantanbanik/Wellread/assets/74443858/7d9c928d-0ce2-4f3f-ace9-b1b0b4e7a7ca)
The form becomes unresponsive to such input

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

Regards,
Chirantan Banik

**Comment by Piyusharora2003** [comment]
Sure , thanks 👍

**Comment by Piyusharora2003** [comment]
![image](https://github.com/chirantanbanik/Wellread/assets/74443858/767e8043-9b5e-4bfc-9d46-2b2d6199d484)

- [ ] Confirm Password is added
- [ ] validation using validator is done

**Comment by Piyusharora2003** [comment]
@chirantanbanik should i make a pull request now

**Comment by chirantanbanik** [comment]
This issue has already been resolved @Piyusharora2003. You can look into other issues
