### ISSUE TITLE
BUG: Redesign Navigation

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#52]
@chirantanbanik 

**Describe the bug**
Navigation not looking good

**Expected behavior**
- Navigation is so simple

**Screenshots**
![image](https://github.com/chirantanbanik/Wellread/assets/114583978/f86907e8-0197-4ec5-ac3a-312cb7d3041b)

we can redesign navigation something like this:
![image](https://github.com/chirantanbanik/Wellread/assets/114583978/ef4d4779-faa3-4f02-a30b-f82717e5de9f)

**Comment by chirantanbanik** [comment]
This issue has already been worked on. Lookout for other issues.
