### ISSUE TITLE
Enhance Readme file 

### ISSUE THREAD

**Issue by aasthakourav20** [chirantanbanik/Wellread#65]
A README file is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers. This file ensures that both new and returning users can easily understand the project's scope, setup, and usage, thereby enhancing the project's accessibility and fostering collaboration

Kindly assign this issue to me under GSSoC'24 .

**Comment by chirantanbanik** [comment]
@aasthakourav20 You can work with @Abhigna-arsam on this issue. You both discuss and come up with an enhanced version of the **Readme.md** file.

**Comment by chirantanbanik** [comment]
@aasthakourav20 This issue is already been worked upon recently. You can look into other issues and work on them.
