### ISSUE TITLE
Preloader

### ISSUE THREAD

**Issue by Jagpreet153** [chirantanbanik/Wellread#66]
**Is your feature request related to a problem? Please describe.**
Yes , addition of a preloader will make gain more interest from user and makes the site more interactive 

**Describe the solution you'd like**
I will add a simple page which contain a svg animation which renders until the page is totally loaded

**Describe alternatives you've considered**
The page would be fully responsive and matching the theme of UI

**Additional context**
Kindly assign this task to me under GSSoC'24

**Comment by Jagpreet153** [comment]
@chirantanbanik Kindly respond to this issue

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
