### ISSUE TITLE
Make user profile 

### ISSUE THREAD

**Issue by AnanyaJain25** [chirantanbanik/Wellread#68]
Making a user profile section which will display name, bio, image and also my posts section. I have experience in implementing this in my past projects

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by chirantanbanik** [comment]
This issue has been worked in the issue #73

**Comment by AnanyaJain25** [comment]
> This issue has been worked in the issue #73

edit profile was extension of this. Before being editable the profile should exist. This includes creation of collection and configuring it and getting data of user to display. #73 as a further part made user details changeable and requires entirely different set of apis
