### ISSUE TITLE
Showing author name on each Post

### ISSUE THREAD

**Issue by AnanyaJain25** [chirantanbanik/Wellread#71]
In "all posts" section only posts are shown this improvement will also display author's name with the post

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md* and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
