### ISSUE TITLE
Integrating OpenAI Api 

### ISSUE THREAD

**Issue by AnanyaJain25** [chirantanbanik/Wellread#74]
Creating a button on each post for users to translate in specific language and get summary of the post. I already have experience in integrating openAI api and writing prompt as per application requirement in my old projects

**Comment by AnanyaJain25** [comment]
Please assign me this under GSSoc @chirantanbanik  !
I would add a special button which will take input post's text automatically and give translated text as per the language mentioned by user.

**Comment by chirantanbanik** [comment]
@AnanyaJain25 The idea is great but we will be keeping it to English only, you can work on the other issues.
