### ISSUE TITLE
Modify the main page navigation bar , add footer , modify the blog icons size , add more feature to navigation bar.

### ISSUE THREAD

**Issue by VipulNerd** [chirantanbanik/Wellread#78]
# Description 
After log in to site, i saw very bad home page. There is no footer.  navigation bar is not of full width and does not have contact us , home button. Also, the navigation bar's top margin is not zero and it's position not static.
Also, the icon size of the blog at home page is uneven, which make site more ugly.
The site does not have a name displayed on it, and the navigation bar lacks a logo.

# Solution 
We can cling the navigation bar to the top and make the width of the navigation bar 100%. Also, we could size all blog button size same. We could also add footer that says all rights reserved and also add social and more features

#  Screenshot of Problem 
<img width="1428" alt="Screenshot 2024-05-31 at 5 00 48 PM" src="https://github.com/chirantanbanik/Wellread/assets/144052913/d185499d-2379-422a-87f2-d1e902e007b6">

# Urgency 
High 

#  Record 
- [x] I have read the contributing guiidlines
- [x] I'm a GSSOC'24 contributor
- [x] I have starred the repository

**Comment by VipulNerd** [comment]
Hi @chirantanbanik I'm @VipulNerd , a GSSOC contributor , I found this as an issue and was hoping you would assign me this. I would be grateful for it

**Comment by chirantanbanik** [comment]
@VipulNerd most of the issues you mentioned are fixed and some are not according to the project vision. You can look into other issues and work on them.
