### ISSUE TITLE
undefined id

### ISSUE THREAD

**Issue by AMISH-KHAN** [chirantanbanik/Wellread#80]
**Describe the bug**
I tried adding a blog but when i click on submit button there in no response and I get an error in the bowser console of undefined Id

**To Reproduce**
1. Go to 'Add post.'
2. Click on 'clisck on submit'
4. See error: no response

**Expected behavior**
There should be a new blog added

**Screenshots**

![image](https://github.com/chirantanbanik/Wellread/assets/123164129/62d774dd-67ea-4064-a0c5-b3f0324b8f52)

Please assign this issue under gssoc

**Comment by chirantanbanik** [comment]
@AMISH-KHAN it's already working, you need fill in with everything and submit.
