### ISSUE TITLE
Adding Forget Password fuctionality

### ISSUE THREAD

**Issue by AnanyaJain25** [chirantanbanik/Wellread#84]
@chirantanbanik  I will be using nodemailer module for the same. A reset link will be shared via mail to user , link will comprise of the unique reset token which will ensure authorised access of the link and then password can be reset.

**Comment by chirantanbanik** [comment]
As the backend is made with Appwrite and not nodejs can nodemailer be used?

**Comment by AnanyaJain25** [comment]
@chirantanbanik sorry for the confusion Being experienced in MERN wrote that previously. I have gone through the appwrite document I will use The Create Password Recovery endpoint which sends the user an email with a temporary secret key for password reset. When the user clicks the confirmation link, they are redirected back to the password reset URL with the secret key and email address values attached to the URL as query strings.
