### ISSUE TITLE
Unequal card size

### ISSUE THREAD

**Issue by root-0101** [chirantanbanik/Wellread#85]
The size of the card of the posts are uneven. So, it would be great if we make the cards of equal size and add some hover effect which makes the UI engaging

![Screenshot 2024-05-31 230424](https://github.com/chirantanbanik/Wellread/assets/142779809/2561396c-a367-413f-a243-42d192585706)

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik
