### ISSUE TITLE
Margin of signup/login

### ISSUE THREAD

**Issue by root-0101** [chirantanbanik/Wellread#86]
As the margin of Login/Signup is not same 

![Screenshot 2024-05-31 230718](https://github.com/chirantanbanik/Wellread/assets/142779809/e08d66b4-7ca9-4830-9575-65c6fb570855)
![Screenshot 2024-05-31 230726](https://github.com/chirantanbanik/Wellread/assets/142779809/1ceccbec-36bf-41e3-be32-c10b44c700ad)

**Comment by chirantanbanik** [comment]
This issue has been already resolved.
