### ISSUE TITLE
Aligning input title in Login and Signup

### ISSUE THREAD

**Issue by richab246** [chirantanbanik/Wellread#88]
**Is your feature request related to a problem? Please describe.**
The input titles on the login and signup forms are not aligned consistently, which affects the visual consistency and user experience.

**Describe the solution you'd like**
Align the input titles on both the login and signup forms to the left for a uniform and professional appearance.

**Additional context**
![Screenshot 2024-06-02 114018](https://github.com/chirantanbanik/Wellread/assets/79681567/3f429add-be0e-46a1-a755-59fbf9803777)

Aligning the titles to the left will enhance the form's readability and overall design.

**Comment by chirantanbanik** [comment]
You can start working on this issue. First of all, go through the code part and understand it. Then, you must read **CONTRIBUTING.MD** and **README.md** and follow the steps that are relevant.
After you are done with the solution to the issue, you have to show a demo.

All the best, and do well.

Regards,
Chirantan Banik

**Comment by richab246** [comment]
Can I also put "Don't have any account?" below the login button, because it's usually there? @chirantanbanik

**Comment by richab246** [comment]
Like this ⬇️
![image](https://github.com/chirantanbanik/Wellread/assets/79681567/982707e9-d42a-413a-9a9b-771981f4c0c1)

**Comment by chirantanbanik** [comment]
Yes sure do that.

**Comment by richab246** [comment]
I have created a pull request for this

**Comment by chirantanbanik** [comment]
Hello @richab246 I needed to talk about certain changes in this, ping me in discord @chirantanbanik.
