### ISSUE TITLE
[Bug] : Card Size changed in responsive devices 

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#95]
**Describe the bug**
@chirantanbanik 

check this out,
when we go to `/all-posts` the card size changed in responsive

**To Reproduce**
1. Go to `all-posts`
2. check in responsive

**Expected behavior**
- it should be in grid layout so it can be responsive

**Screenshots**
![image](https://github.com/chirantanbanik/Wellread/assets/114583978/97950a49-c031-470d-b520-d110965c7589)

**Smartphone (please complete the following information):**
 - Device: `samsung A51/71`
 
**Additional context**

**Comment by chirantanbanik** [comment]
This issue is also under the issue #94
