### ISSUE TITLE
[Bug] : Add Post is not responsive

### ISSUE THREAD

**Issue by dhruv8433** [chirantanbanik/Wellread#96]
**Describe the bug**
@chirantanbanik 

check this out,
add post is not responsive

**To Reproduce**
1. Go to `add post` route
2. cehck in responsive

**Expected behavior**
- we must use grid layout so it can be responsive

**Screenshots**

![image](https://github.com/chirantanbanik/Wellread/assets/114583978/bf1c5502-efa0-4d27-9b28-3a1eddc26159)

**Smartphone (please complete the following information):**
 - Device: `samsung A51/71`

**Additional context**

**Comment by chirantanbanik** [comment]
This issue is also under the issue #94
